books/urls.py
from django.conf.urls import url
from .views import BookListView, BookDetailSlugView, RegisterBooks

urlpatterns = [
    url(r'^$', BookListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', BookDetailSlugView.as_view(), name='detail'),
    url(r'^register-books$', RegisterBooks.as_view(), name='register-books'),

]

profile/urls.py
from django.conf.urls import url
from .views import user_profile, UpdateUserProfile, ProfilePage, error, ConfirmProfile,UpdateStudentProfile,UpdateFacultyProfile


urlpatterns = [
    url(r'^user-profile/$', user_profile, name='user-profile'),
    url(r'^update-user-profile/(?P<pk>\d+)/$', UpdateUserProfile.as_view(), name='update-user-profile'),
    url(r'^update-student-profile/(?P<pk>\d+)/$', UpdateStudentProfile.as_view(), name='update-student-profile'),
    url(r'^update-faculty-profile/(?P<pk>\d+)/$', UpdateFacultyProfile.as_view(), name='update-faculty-profile'),
    url(r'^profile-page/$', ProfilePage.as_view(), name='profile-page'),
    url(r'^error/$', error, name='error'),
    url(r'^confirm-profile/$', ConfirmProfile.as_view(), name='confirm-profile'),

]

recliba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page
from accounts.views import login_page,RegisterView,logout_page,ActivateAccount
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^login/$',login_page, name='login'),
    url(r'^logout/$',logout_page,name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activate-account/(?P<pk>\d+)/$', ActivateAccount.as_view(), name='activate-account'),
    # url(r'^$',home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^', include("books.urls", namespace="books")),
    url(r'^student-register/',include("register.urls", namespace="student-register")),
    # url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^search/', include("search.urls", namespace="search")),
    url(r'^profile/', include("profile.urls", namespace="profile")),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







#url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', product_list_view),
    #url(r'^products/(?P<pk>\d+)/$',ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    #url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    #url(r'^featured/$', ProductFeaturedListView.as_view()),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

register/urls.py
from django.conf.urls import url
from .views import StudentList, RegisterDetail, ReturnBookUpdateRegister, IssueBookUpdateRegister, RegisterStudent,  BookAlreadyIssued, IssueBookFBV, ReturnBookFBV

'''ReturnBookView,IssueBookView,'''
urlpatterns = [
    url(r'^/$', StudentList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/$', RegisterDetail.as_view(), name='detail'),
    url(r'^update-register/(?P<pk>\d+)/$', ReturnBookUpdateRegister.as_view(), name='update'),
    url(r'^issue-update-register/(?P<pk>\d+)/$', IssueBookUpdateRegister.as_view(), name='issue'),
    url(r'^register-student/$', RegisterStudent.as_view(), name='register-student'),
    url(r'^duplicacy/$', BookAlreadyIssued.as_view(), name='duplicacy'),
    url(r'^issue-book/$', IssueBookFBV, name='issue-book'),
    url(r'^return-book/$', ReturnBookFBV, name='return-book'),
]

templates/base/css.html
{% load static %}
 <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<!--Fontawsomecss-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous" />

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<!--J query confirm js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

 <!--Library Custom JS-->
    <!--<script src="{% static 'js/ecommerce.js' %}"></script>-->

templates/base/navbar.html
{% url 'home' as home_url%}
{% url 'profile:profile-page' as profile_url%}
{% url 'books:list' as books_list_url%}
{% url 'login' as login_url%}
{% url 'logout' as logout_url%}
{% url 'register' as register_url%}
{% url 'cart:home' as cart_url%}
{% url 'student-register:list' as student_reg_url %}
{% url 'student-register:issue-book' as issue_url %}
{% url 'student-register:return-book' as return_url %}
{% url 'student-register:register-student' as reg_student_url %}
{% url 'books:register-books' as reg_book_url %}
{% url 'profile:confirm-profile' as confirm_profile_url %}

<nav class="navbar navbar-expand-md mb-3 navbar-dark bg-dark"><div class="container">


    <a class="navbar-brand" href="{{ home_url }}"><img src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">{% if brand_name %} Recliba<!--{{ brand_name }}--> {% else %}Recliba {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">

          <!-- Perfect example
          We can use active only when home page is there
          for that
          <li class="nav-item {% if request.path == home_url %}active{% endif %}">-->

        <!--<a class="nav-link " href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
        {% if request.user.is_staff == False and request.user.is_authenticated %}
      <li class="nav-item {% if request.path == profile_url %}active{% endif %}">
        <a class="nav-link" href="{{ profile_url }}">Profile</a>
      </li>{% endif %}
      <li class="nav-item {% if request.path == books_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ books_list_url }}">Books</a>
      </li>
        {{ request.object  }}
        {% if request.user.is_librarian %}
<li class="nav-item {% if request.path == student_reg_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'student-register:list' %}">Records</a>
      </li>
<li class="nav-item {% if request.path == issue_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'student-register:issue-book' %}">Issue</a>
      </li>

        <li class="nav-item {% if request.path == return_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'student-register:return-book' %}">Return</a>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'student-register:register-student' %}">Register Students</a>
          <a class="dropdown-item" href="{% url 'books:register-books' %}">Register Books</a>
            <a class="dropdown-item" href="{% url 'profile:confirm-profile' %}">Pending Requests</a>

            <!--<div class="dropdown-divider"></div>-->
          <!--<a class="dropdown-item" href="#">Something else here</a>-->
        </div>
         <!--<li class="nav-item {% if request.path == reg_student_url %}active{% endif %}">-->
        <!--<a class="nav-link" href="{% url 'student-register:register-student' %}">Register Students</a>-->
      <!--</li>-->
    <!--<li class="nav-item {% if request.path == reg_book_url %}active{% endif %}">-->
        <!--<a class="nav-link" href="{% url 'books:register-books' %}">Register Books</a>-->
      <!--</li>-->
<!--<li class="nav-item {% if request.path == confirm_profile_url %}active{% endif %}">-->
        <!--<a class="nav-link" href="{% url 'profile:confirm-profile' %}">Pending Requests</a>-->
      <!--</li>-->

       {% endif %}
        {% if request.user.is_authenticated %}

<li class="nav-item">
        <a class="nav-link" href="{{ logout_url }}">Log0ut</a>
      </li>
{% else %}
<li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}"> Login</a>
      </li>
<li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
        {% endif %}
<!--<li class="nav-item {% if request.path == cart_url %}active{% endif %}">-->
        <!--<a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fas fa-shopping-cart"></i> </a>-->
      <!--</li>-->

      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>-->
   <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>-->

    </ul>
      {% include 'search/snippets/search-form.html' %}
  </div>
    </div>

</nav>