books/urls.py
from django.conf.urls import url
from .views import BookListView, BookDetailSlugView, RegisterBooks

urlpatterns = [
    url(r'^$', BookListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', BookDetailSlugView.as_view(), name='detail'),
    url(r'^register-books$', RegisterBooks.as_view(), name='register-books'),

]

recliba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page
from accounts.views import login_page,RegisterView,logout_page,ActivateAccount
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^login/$',login_page, name='login'),
    url(r'^logout/$',logout_page,name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activate-account/(?P<pk>\d+)/$', ActivateAccount.as_view(), name='activate-account'),
    # url(r'^$',home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^', include("books.urls", namespace="books")),
    url(r'^student-register/',include("register.urls", namespace="student-register")),
    # url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^search/', include("search.urls", namespace="search")),
    url(r'^profile/', include("profile.urls", namespace="profile")),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







#url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', product_list_view),
    #url(r'^products/(?P<pk>\d+)/$',ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    #url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    #url(r'^featured/$', ProductFeaturedListView.as_view()),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

register/urls.py
from django.conf.urls import url
from .views import StudentList, RegisterDetail, ReturnBookUpdateRegister, IssueBookUpdateRegister, RegisterStudent,  BookAlreadyIssued, IssueBookFBV, ReturnBookFBV

'''ReturnBookView,IssueBookView,'''
urlpatterns = [
    url(r'^/$', StudentList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/$', RegisterDetail.as_view(), name='detail'),
    url(r'^update-register/(?P<pk>\d+)/$', ReturnBookUpdateRegister.as_view(), name='update'),
    url(r'^issue-update-register/(?P<pk>\d+)/$', IssueBookUpdateRegister.as_view(), name='issue'),
    url(r'^register-student/$', RegisterStudent.as_view(), name='register-student'),
    url(r'^duplicacy/$', BookAlreadyIssued.as_view(), name='duplicacy'),
    url(r'^issue-book/$', IssueBookFBV, name='issue-book'),
    url(r'^return-book/$', ReturnBookFBV, name='return-book'),
]

register/forms.py
from django import forms
class RegisterUpdateForm(forms.ModelForm):#widget for ading html classes customizing django widgets
    return_date=forms.DateField(widget=forms.DateInput(attrs={"class":"form-control","placeholder":"Your Email"}))
    # status=forms.BooleanField(widget=forms.BooleanInput(
    #                           attrs={
    #                               "class":"form-control",
    #                               "placeholder":"Your Full Name"}))
class IssueForm(forms.Form):
    roll=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control","placeholder":"Roll No"}))

class ReturnForm(forms.Form):
    book=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control","placeholder":"Book No"}))

register/views.py
from django.shortcuts import render
from .models import StudentRegister, BookRegister , booksissued_post_save_receiver
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect, HttpResponse
from datetime import date, timedelta
from books.models import Book
from django.shortcuts import redirect
from django.db.models import Q
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import RegisterUpdateForm, IssueForm, ReturnForm
from profile.models import UserProfile
today = date.today()
class StudentList(ListView):
    @method_decorator(user_passes_test(lambda u: u.is_librarian))#u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    template_name = 'register/list.html'
    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None)  # method_dict['q']
        if query is not None:
            lookups = Q(name__icontains=query) | Q(roll_no__icontains=query) | Q(batch__icontains=query)
            return StudentRegister.objects.filter(lookups)
        return StudentRegister.objects.all()


def length(x):
    s = 0
    while(x >0):
        s=s+1
        x=x/10
    return s

class RegisterDetail(DetailView):
    @method_decorator(user_passes_test(lambda u:  u.is_librarian))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    template_name = 'register/detail.html'
    def get_object(self, *args, **kwargs):
        request = self.request
        id = self.kwargs.get('pk')
        try:
            instance = []
            instance.append(BookRegister.objects.get(student=StudentRegister.objects.filter(id=id)))
        except BookRegister.DoesNotExist:
            instance = []
            instance.append(StudentRegister.objects.get(id=id))
        except BookRegister.MultipleObjectsReturned:
            qs = BookRegister.objects.filter(student=StudentRegister.objects.filter(id=id)).all()
            instance = []
            for i in qs:
                instance.append(i)
        except:
            raise Http404("Uhmm")
        return instance

# class IssueBookUpdateRegister(CreateView):
#         template_name = 'register/issue.html'
#         model = BookRegister
#         fields = ['student','book_no']
#
#         def form_valid(self, form):
#             obj = form.save(commit=False)
#             obj.new = False
#             obj.status = False
#             obj.save()
#             x = obj.book_no
#             x = int(x / 100)
#             obj.book = Book.objects.get(isbn__iexact=x)
#             obj.due_date = obj.issue_date + timedelta(days=15)
#             obj.save()
#             booksissued_post_save_receiver(instance=obj, sender=BookRegister)
#             #post_save.connect(booksissued_post_save_receiver, sender=BookRegister)
#             return HttpResponseRedirect(reverse_lazy('student-register:list'))
#
#
#         success_url = reverse_lazy('student-register:list')

class IssueBookUpdateRegister(UpdateView):
        '''Class Based View for issuing book'''
        @method_decorator(user_passes_test(lambda u:  u.is_librarian))
        def dispatch(self, *args, **kwargs):
            return super().dispatch(*args, **kwargs)

        template_name = 'register/issue.html'
        model = BookRegister
        fields = ['book_no','due_date']

        def form_valid(self, form):
            obj = form.save(commit=False)
            obj.new = False
            obj.status = False
            obj.save()
            x = obj.book_no
            try:
                objb = BookRegister.objects.filter(book_no__iexact=x, status=False)
                y = 0
                for i in objb:
                    y += 1
                if(y==1):
                    x = int(x / 100)
                    obj.book = Book.objects.get(isbn__iexact=x)
                    if obj.book.less_quantity:
                        print(obj.book.copies,obj.book.less_quantity)
                        return HttpResponse("<h1>Sorry! Only a few amount of the book is available in the library<a href="">Go back</a></h1>")
                    if obj.due_date is None:
                        obj.due_date = obj.issue_date + timedelta(days=15)
                    obj.save()
                    booksissued_post_save_receiver(instance=obj, sender=BookRegister)
                    # post_save.connect(booksissued_post_save_receiver, sender=BookRegister)
                    return HttpResponseRedirect(reverse_lazy('student-register:issue-book'))
                else:
                    return HttpResponseRedirect(reverse_lazy('student-register:duplicacy'))
            except:
                return HttpResponse("<h2>Sorry The book is not avialable</h2>")

class RegisterStudent(CreateView):
    @method_decorator(user_passes_test(lambda u: u.is_librarian))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    template_name = 'register/student_form.html'
    model = StudentRegister
    fields = ['name', 'roll_no', 'batch', 'year']
    success_url = reverse_lazy('student-register:list')


class ReturnBookUpdateRegister(UpdateView):
        @method_decorator(user_passes_test(lambda u:  u.is_librarian))
        def dispatch(self, *args, **kwargs):
            return super().dispatch(*args, **kwargs)

        template_name = 'register/register_update_form.html'
        model = BookRegister
        fields=['fine']

        def form_valid(self, form):
            obj = form.save(commit=False)
            obj.status = True
            obj.return_date=today
            obj.save()
            booksissued_post_save_receiver(instance=obj, sender=BookRegister)
            obj.save()
            return HttpResponseRedirect(reverse_lazy('student-register:return-book'))
        success_url=reverse_lazy('student-register:return-book')

# class ReturnBookView(ListView):
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         return super().dispatch(*args, **kwargs)
#
#     template_name = "register/returnview.html"
#
#     def get_queryset(self, *args, **kwargs):
#         request = self.request
#         method_dict=request.GET
#         query = method_dict.get('q',None) # method_dict['q']
#         if query is not None:
#             return BookRegister.objects.filter(book_no__iexact=query, status=False)
#         return

# class IssueBookView(ListView):
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         return super().dispatch(*args, **kwargs)
#
#     template_name = "register/issueview.html"
#     def get_queryset(self, *args, **kwargs):
#         blank_obj = BookRegister.objects.filter(book=None)
#         blank_obj.delete()
#         request = self.request
#         method_dict=request.GET
#         query = method_dict.get('q',None) # method_dict['q']
#         if query is not None:
#             if(StudentRegister.objects.filter(roll_no__iexact=query)):
#                 obj = StudentRegister.objects.get(roll_no__iexact=query)
#                 obj1 = StudentRegister.objects.get(roll_no__iexact=query)
#                 obj2 = BookRegister.objects.filter(student=obj1, new=False)
#                 objs = StudentRegister.objects.get(roll_no__iexact=query)
#                 y = objs.books_issued
#                 if(y<10):
#                     BookRegister.objects.create(student=obj)
#                     return BookRegister.objects.filter(student=obj1, new=True)
#                 if(y>=10):
#                     return y
#         return False

class BookAlreadyIssued(ListView):
    @method_decorator(user_passes_test(lambda u:  u.is_librarian))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    template_name = 'register/duplicacy.html'
    queryset = BookRegister.objects.filter(book=None, status=False, new=False)
@login_required
def IssueBookFBV(request):
    form = IssueForm(request.POST or None)
    context = {'form': form}
    user = UserProfile.objects.get(user=request.user)
    if(request.user.is_librarian):
        try:
            blank_obj = BookRegister.objects.filter(book=None)
            blank_obj.delete()
        except:
            pass
        if form.is_valid():
            roll_no = form.cleaned_data.get("roll")
            try:
                student = StudentRegister.objects.get(roll_no=roll_no)
                y = student.books_issued
                if (y < 10):
                    BookRegister.objects.create(student=student)
                    obj = BookRegister.objects.get(student=student, new=True)
                    return redirect(reverse('student-register:issue',kwargs={'pk':obj.id}))
                else:
                    context = {'form':form,
                               'error':"Sorry You have exceeded the limit of 10 issues"}
            except:# StudentRegister matching query does not exist:
              context = {'form':form,'register':'Please Register First'}

        return render(request,"register/issuefbv.html",context)
    else:
        context = {'error':"Sorry you can't see this page"}
        raise Http404("Page does not exists")

@login_required
def ReturnBookFBV(request):
    form = ReturnForm(request.POST or None)
    context = {'form': form}
    user = UserProfile.objects.get(user=request.user)
    if(request.user.is_librarian):
        blank_obj = BookRegister.objects.filter(book=None)
        blank_obj.delete()

register/templates/register/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% for obj in object %}
    <div class="row"><div class="col-12 ">
        {% if forloop.first %}
        <h3>Student Details</h3><br/></div></div>
    <div class="row"><div class="col-6 ">
        Name: {{ obj.student.name }} {{obj.name}}<br/></div>
    <div class="col-6 ">
       Roll No: {{ obj.student.roll_no }}  {{obj.roll_no}}<br/></div></div>

    <div class="row"><div class="col-6 ">
       Batch: {{ obj.student.batch }} {{obj.batch}} <br/></div>

    <div class="col-6 ">
       Year: {{ obj.student.year }} {{obj.year}} <br/></div></div>
    <div class="row"><div class="col-12  "><d><hr/></d></div></div>{% endif %}
{% endfor %}

    <table class="table">
  <thead>
    <tr>
      <th scope="col">S No.</th>
      <th scope="col">Book Name</th>
      <th scope="col">Book No.</th>
      <th scope="col">Issue Date</th>
      <th scope="col" >Due Date</th>
      <th scope="col">Return Date</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in object %}
  <tr>{% if obj.book %}
      <th scope="row">{{forloop.counter}}</th>
        <td>{{ obj.book.name }}
        </td>
      <td>{{ obj.book_no }}</td>
      <td>{{ obj.issue_date }}</td>
      <td {% if obj.is_past_due %}style="font-weight:bold;color:red;"{% endif %}>{{ obj.due_date }}</td>
      <td>{{ obj.return_date }}</td>
      <td>{% if  obj.status  %}Returned{% else %} <!--<a href="{% url 'student-register:update' obj.id %}" clas-->Not Returned<!--</a>--> {% endif %}</td>
{% endif %}
    </tr>{% endfor %}
    </tbody>
</table>
{% for obj in object %}{% if forloop.first %}
    <div class="row"><div class="col-12 ">
        {% if obj.student.books_issued != 10  %}
<a href="{% url 'student-register:issue-book' %}" class="btn btn-success btn-sm btn-block" role="button" aria-pressed="true">Issue Book</a>

        {% endif %} </div></div>
{% endif %}
{% endfor %}


{% endblock %}

register/templates/register/duplicacy.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col">
    <h3>Sorry!! The Book is already issued</h3>
</div></div>

{% for obj in object_list %}
        <a class="btn btn-success btn-sm " role="button" aria-pressed="true" href="{% url 'student-register:issue' obj.id %}">Go Back</a>
{% endfor %}
{% endblock %}

register/templates/register/issue.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col"><h1>Issue Books</h1></div></div>
<div class="row"><div class="col"><hr/></div></div>
<div class="row"><div class="col-12 ">
        <h3>Student Details</h3><br/></div></div>
    <div class="row"><div class="col-6 ">
        Name: {{ object.student.name }} {{obj.name}}<br/></div>
    <div class="col-6 ">
       Roll No: {{ object.student.roll_no }}  {{obj.roll_no}}<br/></div></div>

    <div class="row"><div class="col-6 ">
       Batch: {{ object.student.batch }} {{obj.batch}} <br/></div>

    <div class="col-6 ">
       Year: {{ object.student.year }} {{obj.year}} <br/></div></div>
    <div class="row"><div class="col-12  "><d><hr/></d></div></div>


<form action="" method="post">{% csrf_token %}
    <div class="row"><div class="col"><br/></div></div>


<div class="row"><div class="col">ISBN: {{ form.book_no }}</div><div class="col">Due Date: {{ form.due_date }}</div></div>

<div class="row"><div class="col"><br/></div></div>

    <button type="submit" class="btn btn-success btn-sm btn-block">Submit</button>
</form>
{% endblock %}

register/templates/register/issuefbv.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col">
    <h1>Issue Panel</h1><br/><hr/>
</div></div>
<form method="POST">{%csrf_token%}
<div class="form-row ">
    <div class="form-group col-lg-5 col-md-3 mx-auto ">
    {{form.roll}}
    </div>
    <div class="form-group col-lg-2 col-md-3 mx-auto ">
<button type="submit" class="btn btn-success btn-sm ">Submit</button>
    </div>
</div>

<br/>
</form>
<div class="row"><div class="col" style="font-weight:bold;color:red;">{{error}}{{register}}
</div></div>
{% endblock %}

register/templates/register/issueview.html
{% extends 'base.html' %}

{% block content %}
<div class="row mb-3">
    {% if query %}
    <div class="col-12 col-md-6  py-5">
      <h1>Details</h1>
 </div>

        <div class="col-12"><hr/>
        </div>
    {% else %}
    <div class="col-12 col-md-6 mx-auto py-5">
       {% include 'search/snippets/issue-form.html' %}
 </div>
        <div class="col-12"><hr/>
        </div>
    {% endif %}
    {% if  object_list >= 10 %}
    <div class="row"  ><div class="col" > Sorry You Have exceeded your limit</div></div>
    {% else %}{% if object_list != False %}
</div>{% for obj in object_list %}
<br/><div class="row"><div class="col">
        <h1>Details</h1>
    </div></div>
<div class="row"><div class="col">
     Student Name: {{ obj.student.name }}
    </div>
<div class="col">Roll No: {{ obj.student.roll_no }}</div>
</div>
<div class="row"><div class="col">
     Batch: {{ obj.student.batch }}
    </div>
<div class="col">Year: {{ obj.student.year }}</div>
</div>
<div class="row"><div class="col">
     Books Issued: {{ obj.student.books_issued }}
    </div>
</div>


    <div class="row">
    <div class="col">
   <a href="{% url 'student-register:issue' obj.id %}" class="btn btn-success btn-sm " role="button" aria-pressed="true">Issue</a>
   </div></div>{% endfor %}{% endif %}{% endif %}
{% if object_list == False %}
<div class="row">
     <div class="col-12 py-5">
    <h1>Please register first</h1><a href="{% url 'student-register:register-student' %}" class="btn btn-success btn-sm " role="button" aria-pressed="true">Register Student</a>
   </div></div>
{% endif %}

{% endblock %}

register/templates/register/list.html
{% extends 'base.html' %}
{% url 'student-register:detail' as student_url %}
{% block content %}
<div class="row">
    <div class="col"><h1>Student Records</h1><hr/><br/></div>
</div>
<div class="row"><div class="col-5 mx-auto">
     {% include 'search/snippets/student-record.html' %}<hr/><br/>
</div></div>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">S No.</th>
      <th scope="col">Name</th>
      <th scope="col">Roll No.</th>
      <th scope="col">Batch</th>
      <th scope="col">Year</th>
      <th scope="col">Books issued</th>
      <th scope="col">Total Books Issued</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
  <tr>
      <th scope="row">{{forloop.counter}}</th>
        <td><a href="{{ student_url }}{{obj.id}}">{{ obj.name }}</a>
        </td>
      <td>{{ obj.roll_no }}</td>
      <td>{{ obj.batch }}</td>
      <td>{{ obj.year }}</td>
      <td>{{ obj.books_issued }}</td>
      <td>{{ obj.books_issued_tilldate }}</td>

    </tr>{% endfor %}
    </tbody>
</table>{% endblock %}


we can also use

{ if obj.title=="Something" %}

{ endif %}

register/templates/register/register_update_form.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col-12 ">
        <h3>Student Details</h3><br/></div></div>
    <div class="row"><div class="col-6 ">
        Name: {{ object.student.name }} {{obj.name}}<br/></div>
    <div class="col-6 ">
       Roll No: {{ object.student.roll_no }}  {{obj.roll_no}}<br/></div></div>

    <div class="row"><div class="col-6 ">
       Batch: {{ object.student.batch }} {{obj.batch}} <br/></div>

    <div class="col-6 ">
       Year: {{ object.student.year }} {{obj.year}} <br/></div></div>
    <div class="row"><div class="col-12  "><d><hr/></d></div></div>

<div class="row"><div class="col-12 ">
        <h3>Book Details</h3></div>
    <div class="col-6 ">
       Title: {{ object.book.title }}  <br/></div>
    <div class="col-6 ">
       Author:  {{ object.book.author }}  <br/></div>

</div>
<div class="row">
    <div class="col-6 ">
       Price: {{ object.book.price }}  <br/></div>
    <div class="col-6 ">
       Book No.: {{ object.book_no }}  <br/></div>

</div>
<form action="" method="post">{% csrf_token %}
    <div class="row"><div class="col-12  "><d><hr/></d></div></div>
 <div class="row"><div class="col-12  ">Issue Date:{{object.issue_date}}</div></div>
<div class="row">
    <div class="col-6 " {% if object.is_past_due %}style="font-weight:bold;color:red;"{% endif %}>
       Due Date    :{{object.due_date}}  <br/></div>
 <div class="col-6 " {% if object.is_past_due %}style="font-weight:bold;color:red;"{% endif %}>
       Fine: {{object.fine}}{{form.fine}}  <br/></div>

</div>

    <div class="row"><div class="col-12  "><d><hr/></d></div></div>
<div class="row">

    <div class="col">    <button type="submit" class="btn btn-danger"> Return </button><div>

</form></div>
<div class="row">
    <div class="col-8">  <br/>
</div>

<!--<div class="row">-->
    <!--<div class="col"><a href="{% url 'student-register:issue-book' %}" class="btn btn-success">ReIssue</a></div>-->
<!--</div>-->
{% endblock %}

register/templates/register/reissue_page.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col"><h1>Issue Books</h1></div></div>
<div class="row"><div class="col"><hr/></div></div>
<div class="row"><div class="col-12 ">
        <h3>Student Details</h3><br/></div></div>
    <div class="row"><div class="col-6 ">
        Name: {{ object.student.name }} {{obj.name}}<br/></div>
    <div class="col-6 ">
       Roll No: {{ object.student.roll_no }}  {{obj.roll_no}}<br/></div></div>

    <div class="row"><div class="col-6 ">
       Batch: {{ object.student.batch }} {{obj.batch}} <br/></div>

    <div class="col-6 ">
       Year: {{ object.student.year }} {{obj.year}} <br/></div></div>
    <div class="row"><div class="col-12  "><d><hr/></d></div></div>


{% endblock %}

register/templates/register/return.html
{% extends 'base.html' %}
{% block content %}
{% include 'search/snippets/return-form.html' %}
{% endblock %}

register/templates/register/returnfbv.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col">
    <h1>Return Panel</h1><br/><hr/>
</div></div>
<form method="POST">{%csrf_token%}
<div class="form-row ">
    <div class="form-group col-lg-5 col-md-3 mx-auto ">
    {{form.book}}
    </div>
    <div class="form-group col-lg-2 col-md-3 mx-auto ">
<button type="submit" class="btn btn-success btn-sm ">Submit</button>
    </div>
</div>

<br/>
</form>
<div class="row"><div class="col" style="font-weight:bold;color:red;">{{error}}{{register}}
</div></div> 
{% endblock %}

register/templates/register/returnview.html
{% extends 'base.html' %}

{% block content %}
<div class="row mb-3">
    {% if query %}
    <div class="col-12 col-md-6  py-5">
      <h1>Details</h1>
 </div>

        <div class="col-12"><hr/>
        </div>
    {% else %}
    <div class="col-12 col-md-6 mx-auto py-5">
       {% include 'search/snippets/return-form.html' %}
 </div>
        <div class="col-12"><hr/>
        </div>
    {% endif %}

</div>
<div class="row"><div class="col">
    {% for obj in object_list %}
    Student Name : {{obj.student.name}}</div></div>

<div class="row"><div class="col">
Book : {{ obj.book.title }}
</div></div>

<div class="row"><div class="col">
Book No: {{ obj.book_no }}
</div></div>

<br/><div class="row"><div class="col">
   <a href="{% url 'student-register:update' obj.id %}" class="btn btn-success btn-sm " role="button" aria-pressed="true">Return</a>
    {% endfor %}
</div></div>
{% endblock %}

register/templates/register/student_form.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><div class="col">
    <h1>Register Students</h1>
</div></div>
<div class="row"><div class="col">
    <h1><hr/></h1>
</div></div>
<br/>
<form action="" method="post">{% csrf_token %}
    <div class="row"><div class="col">
        {% if form is None %}
        <h3>Student with given roll number already exits</h3>
        {% endif %}
        Name:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.name }}</div>
    <div class="col">
        Roll No:&nbsp&nbsp&nbsp{{ form.roll_no }}
        </div>
     </div><br/>
    <div class="row"><div class="col">Batch:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.batch }}</div>
    <div class="col">
        Year:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.year }}
        </div>
     </div>
<br/>
    <button type="submit" class="btn btn-success btn-sm btn-block">Submit</button>
</form>
{% endblock %}