books/urls.py
from django.conf.urls import url
from .views import BookListView, BookDetailSlugView, RegisterBooks

urlpatterns = [
    url(r'^$', BookListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', BookDetailSlugView.as_view(), name='detail'),
    url(r'^register-books$', RegisterBooks.as_view(), name='register-books'),

]

recliba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page,about_page,contact_page
from accounts.views import login_page,RegisterView,logout_page,ActivateAccount
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^login/$',login_page, name='login'),
    url(r'^logout/$',logout_page,name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activate-account/(?P<pk>\d+)/$', ActivateAccount.as_view(), name='activate-account'),
    # url(r'^$',home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^', include("books.urls", namespace="books")),
    url(r'^student-register/',include("register.urls", namespace="student-register")),
    # url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^search/', include("search.urls", namespace="search")),
    url(r'^profile/', include("profile.urls", namespace="profile")),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







#url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', product_list_view),
    #url(r'^products/(?P<pk>\d+)/$',ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    #url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    #url(r'^featured/$', ProductFeaturedListView.as_view()),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

register/urls.py
from django.conf.urls import url
from .views import StudentList, RegisterDetail, ReturnBookUpdateRegister, IssueBookUpdateRegister, RegisterStudent,  BookAlreadyIssued, IssueBookFBV, ReturnBookFBV

'''ReturnBookView,IssueBookView,'''
urlpatterns = [
    url(r'^/$', StudentList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/$', RegisterDetail.as_view(), name='detail'),
    url(r'^update-register/(?P<pk>\d+)/$', ReturnBookUpdateRegister.as_view(), name='update'),
    url(r'^issue-update-register/(?P<pk>\d+)/$', IssueBookUpdateRegister.as_view(), name='issue'),
    url(r'^register-student/$', RegisterStudent.as_view(), name='register-student'),
    url(r'^duplicacy/$', BookAlreadyIssued.as_view(), name='duplicacy'),
    url(r'^issue-book/$', IssueBookFBV, name='issue-book'),
    url(r'^return-book/$', ReturnBookFBV, name='return-book'),
]

search/urls.py
from django.conf.urls import url
from books.views import BookListView
from .views import SearchBookView

urlpatterns = [
    url(r'^/$', SearchBookView.as_view(), name='query'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from books.models import Book
from django.views.generic import ListView
class SearchBookView(ListView):
    template_name = "search/view.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchBookView, self).get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context


    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict=request.GET
        query = method_dict.get('q',None) # method_dict['q']
        #print(query)
        if query is not None:
            return Book.objects.search(query)
        return Book.objects.featured()
    '''
    __icontains = field contains this
    __ieaxct = field is exactly this
    '''

search/templates/search/snippets/issue-form.html
  <form method="GET" action="{% url "student-register:issue-book" %}" class="form ml-auto">
      <div class="input-group">
        <input class="form-control " type="search" placeholder="Enter Roll Number" name="q" aria-label="Search" value="{{request.GET.q}}">
       <span class="input-group-btn">
        <button class="btn btn-outline-success " type="submit">Enter</button>
    </span></div></form>

search/templates/search/snippets/return-form.html
  <form method="GET" action="{% url "student-register:return-book" %}" class="form ml-auto">
      <div class="input-group">
        <input class="form-control " type="search" placeholder="Enter Book Number" name="q" aria-label="Search" value="{{request.GET.q}}">
       <span class="input-group-btn">
        <button class="btn btn-outline-success " type="submit">Enter</button>
    </span></div></form>

search/templates/search/snippets/search-form.html
{% url 'search:query' as search_url %}
<form method="GET" action="{% url "search:query" %}" class="form ml-auto">
      <div class="input-group">
        <input class="form-control form-control-sm " type="search" placeholder="Search Books" name="q" aria-label="Search" value="{% if request.path == search_url %}{{request.GET.q}}{% endif %}">
       <span class="input-group-btn">
        <button class="btn btn-outline-success btn-sm " type="submit">Search</button>
    </span></div></form>

search/templates/search/snippets/student-record.html
  <form method="GET" action="{% url "student-register:list" %}" class="form ml-auto">
      <div class="input-group">
        <input class="form-control form-control-sm " type="search" placeholder="Search Student Records" name="q" aria-label="Search" value="{{request.GET.q}}">
       <span class="input-group-btn">
        <button class="btn btn-outline-success btn-sm " type="submit">Enter</button>
    </span></div></form>